In [1]:
# Import modules
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

In [2]:
# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(
    Path('clean_train.csv')   
)

# Review the DataFrame
df.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [4]:
test_data = pd.read_csv(
    Path('clean_test.csv')   
)

#test_data.drop('Cover_Type', axis=1, inplace=True)

test_data.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,2680,354,14,0,0,2684,196,214,156,6645,...,0,0,0,0,0,0,0,0,0,0
1,2683,0,13,0,0,2654,201,216,152,6675,...,0,0,0,0,0,0,0,0,0,0
2,2713,16,15,0,0,2980,206,208,137,6344,...,0,0,0,0,0,0,0,0,0,0
3,2709,24,17,0,0,2950,208,201,125,6374,...,0,0,0,0,0,0,0,0,0,0
4,2706,29,19,0,0,2920,210,195,115,6404,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10', 'Soil_Type11',
       'Soil_Type12', 'Soil_Type13', 'Soil_Type14', 'Soil_Type16',
       'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20',
       'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24',
       'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28',
       'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32',
       'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36',
       'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_Type40',
       'Cover_Type'],
      dtype='object')

In [6]:
df.describe()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,...,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000
mean,2749.322553,156.676653,16.501587,227.195701,51.076521,1714.023214,212.704299,218.965608,135.091997,1511.147288,...,0.045635,0.040741,0.001455,0.006746,0.000661,0.002249,0.048148,0.043452,0.030357,4.000000
std,417.678187,110.085801,8.453927,210.075296,61.239406,1325.066358,30.561287,22.801966,45.895189,1099.936493,...,0.208699,0.197696,0.038118,0.081859,0.025710,0.047368,0.214086,0.203880,0.171574,2.000066
min,1863.000000,0.000000,0.000000,0.000000,-146.000000,0.000000,0.000000,99.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2376.000000,65.000000,10.000000,67.000000,5.000000,764.000000,196.000000,207.000000,106.000000,730.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,2752.000000,126.000000,15.000000,180.000000,32.000000,1316.000000,220.000000,223.000000,138.000000,1256.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,3104.000000,261.000000,22.000000,330.000000,79.000000,2270.000000,235.000000,235.000000,167.000000,1988.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
max,3849.000000,360.000000,52.000000,1343.000000,554.000000,6890.000000,254.000000,254.000000,248.000000,6993.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

In [7]:
df.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10', 'Soil_Type11',
       'Soil_Type12', 'Soil_Type13', 'Soil_Type14', 'Soil_Type16',
       'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20',
       'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24',
       'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28',
       'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32',
       'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36',
       'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_Type40',
       'Cover_Type'],
      dtype='object')

In [8]:
df.shape

(15120, 53)

In [9]:
df['Cover_Type'].value_counts()

5    2160
2    2160
1    2160
7    2160
3    2160
6    2160
4    2160
Name: Cover_Type, dtype: int64

In [10]:
# Seperate the features, X,  from the target variable, y
y = df['Cover_Type']
X = df.drop(columns='Cover_Type')

In [11]:
# Preview the features data
X.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,0
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# Preview the first five entries for the target variable
y[:5]

0    5
1    5
2    2
3    2
4    5
Name: Cover_Type, dtype: int64

In [13]:
df.dtypes

Elevation                             int64
Aspect                                int64
Slope                                 int64
Horizontal_Distance_To_Hydrology      int64
Vertical_Distance_To_Hydrology        int64
Horizontal_Distance_To_Roadways       int64
Hillshade_9am                         int64
Hillshade_Noon                        int64
Hillshade_3pm                         int64
Horizontal_Distance_To_Fire_Points    int64
Wilderness_Area1                      int64
Wilderness_Area2                      int64
Wilderness_Area3                      int64
Wilderness_Area4                      int64
Soil_Type1                            int64
Soil_Type2                            int64
Soil_Type3                            int64
Soil_Type4                            int64
Soil_Type5                            int64
Soil_Type6                            int64
Soil_Type8                            int64
Soil_Type9                            int64
Soil_Type10                           int64
Soil_Type11                           int64
Soil_Type12                           int64
Soil_Type13                           int64
Soil_Type14                           int64
Soil_Type16                           int64
Soil_Type17                           int64
Soil_Type18                           int64
Soil_Type19                           int64
Soil_Type20                           int64
Soil_Type21                           int64
Soil_Type22                           int64
Soil_Type23                           int64
Soil_Type24                           int64
Soil_Type25                           int64
Soil_Type26                           int64
Soil_Type27                           int64
Soil_Type28                           int64
Soil_Type29                           int64
Soil_Type30                           int64
Soil_Type31                           int64
Soil_Type32                           int64
Soil_Type33                           int64
Soil_Type34                           int64
Soil_Type35                           int64
Soil_Type36                           int64
Soil_Type37                           int64
Soil_Type38                           int64
Soil_Type39                           int64
Soil_Type40                           int64
Cover_Type                            int64
dtype: object

In [14]:
# Split the dataset using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [15]:
# Instantiate a StandardScaler instance
scaler = StandardScaler()

# Fit the training data to the standard scaler
X_scaler = scaler.fit(X_train)

# Transform the training data using the scaler
X_train_scaled = X_scaler.transform(X_train)

# Transform the testing data using the scaler
X_test_scaled = X_scaler.transform(X_test)

In [16]:
# Import the KNeighborsClassifier module from sklearn
from sklearn.neighbors import KNeighborsClassifier

# Instantiate the KNeighborsClassifier model with n_neighbors = 3 
knn = KNeighborsClassifier(n_neighbors=3)

In [17]:
# Train the model using the training data
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
# Create predictions using the testing data
y_pred = knn.predict(X_test_scaled)

In [19]:
# Print the classification report comparing the testing data to the model predictions
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.69      0.67      0.68       552
           2       0.70      0.55      0.61       561
           3       0.77      0.73      0.75       530
           4       0.90      0.94      0.92       563
           5       0.79      0.93      0.86       513
           6       0.75      0.79      0.77       529
           7       0.90      0.94      0.92       532

    accuracy                           0.79      3780
   macro avg       0.79      0.79      0.79      3780
weighted avg       0.79      0.79      0.79      3780

In [20]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

In [21]:
lr_model=LogisticRegression(max_iter=200,random_state=1)
rf_model=RandomForestClassifier(random_state=56,n_estimators=20)
gnb_model=GaussianNB(var_smoothing=1e-03)
#svc_model=SVC(kernel='linear',degree=2)
bg_model=BaggingClassifier(n_estimators=13,random_state=2)
#knn_model=KNeighborsClassifier(n_neighbors=20)

models={"LogisticRegression":lr_model,
        'RandomForest':rf_model,
        'GaussianNB':gnb_model,
        'BaggingClassifier':bg_model,}
        #'KNeighborsClassifier':knn_model}

for x in models:
    model=models[x]
    model.fit(X_train,y_train)
    predictions=model.predict(X_test)
    print(f'*******   {x}   ******')
    print(f"balanced accuracy score: {balanced_accuracy_score(y_test, predictions)}")
    # Print the classification report for the model
    target_names = ["Spruce/Fir", "Lodgepole Pine", "Ponderosa Pine", "Cottonwood/Willow", "Aspen", "Douglas-fir", "Krummholz"]
    print(classification_report(y_test, predictions, target_names=target_names))
    print('*'*40)

*******   LogisticRegression   ******
balanced accuracy score: 0.5123943063435886
                   precision    recall  f1-score   support

       Spruce/Fir       0.45      0.46      0.46       552
   Lodgepole Pine       0.41      0.39      0.40       561
   Ponderosa Pine       0.48      0.41      0.44       530
Cottonwood/Willow       0.75      0.80      0.77       563
            Aspen       0.43      0.50      0.46       513
      Douglas-fir       0.40      0.37      0.38       529
        Krummholz       0.63      0.67      0.65       532

         accuracy                           0.51      3780
        macro avg       0.51      0.51      0.51      3780
     weighted avg       0.51      0.51      0.51      3780

****************************************
*******   RandomForest   ******
balanced accuracy score: 0.8502140095173844
                   precision    recall  f1-score   support

       Spruce/Fir       0.74      0.76      0.75       552
   Lodgepole Pine       0.77      0.64      0.70       561
   Ponderosa Pine       0.83      0.83      0.83       530
Cottonwood/Willow       0.94      0.96      0.95       563
            Aspen       0.88      0.92      0.90       513
      Douglas-fir       0.84      0.88      0.86       529
        Krummholz       0.92      0.96      0.94       532

         accuracy                           0.85      3780
        macro avg       0.85      0.85      0.85      3780
     weighted avg       0.85      0.85      0.85      3780

****************************************
*******   GaussianNB   ******
balanced accuracy score: 0.5967886808661833
                   precision    recall  f1-score   support

       Spruce/Fir       0.59      0.60      0.59       552
   Lodgepole Pine       0.51      0.28      0.36       561
   Ponderosa Pine       0.54      0.33      0.41       530
Cottonwood/Willow       0.69      0.82      0.75       563
            Aspen       0.52      0.78      0.62       513
      Douglas-fir       0.50      0.53      0.52       529
        Krummholz       0.77      0.83      0.80       532

         accuracy                           0.60      3780
        macro avg       0.59      0.60      0.58      3780
     weighted avg       0.59      0.60      0.58      3780

****************************************
*******   BaggingClassifier   ******
balanced accuracy score: 0.8461751600386208
                   precision    recall  f1-score   support

       Spruce/Fir       0.73      0.72      0.72       552
   Lodgepole Pine       0.74      0.63      0.68       561
   Ponderosa Pine       0.86      0.83      0.84       530
Cottonwood/Willow       0.95      0.97      0.96       563
            Aspen       0.86      0.93      0.89       513
      Douglas-fir       0.86      0.90      0.88       529
        Krummholz       0.90      0.95      0.92       532

         accuracy                           0.84      3780
        macro avg       0.84      0.85      0.84      3780
     weighted avg       0.84      0.84      0.84      3780

****************************************

In [22]:
for x in models:
    model = models[x]
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    test_data[x + 'Cover_Type'] = predictions

ValueError: Length of values (3780) does not match length of index (565784)

In [19]:
lr_model.fit(X_train,y_train)
predictions=lr_model.predict(X_test)

In [24]:
rf_model.fit(X_train,y_train)
predictions=rf_model.predict(X_test)

In [29]:
gnb_model.fit(X_train,y_train)
predictions=gnb_model.predict(X_test)

In [34]:
bg_model.fit(X_train,y_train)
predictions=bg_model.predict(X_test)

In [35]:
print(predictions)

[6 2 7 ... 5 2 4]

In [24]:
test_data['Cover_Type'] = predictions
test_data.to_csv('rf_model_test_predictions.csv', index=False)

ValueError: Length of values (145253) does not match length of index (581012)

In [36]:
df_predictions = pd.DataFrame({'Cover_Type': predictions})
df_predictions.head()

   Cover_Type
0           6
1           2
2           7
3           5
4           2

In [37]:
test_data['Cover_Type'] = df_predictions
test_data.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,6.0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,2.0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,7.0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,5.0
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,2.0

In [23]:
test_data['Cover_Type'] = df_predictions
test_data.to_csv('lr_model_test_predictions.csv', index=False)

In [28]:
test_data['Cover_Type'] = df_predictions
test_data.to_csv('rf_model_test_predictions.csv', index=False)

In [33]:
test_data['Cover_Type'] = df_predictions
test_data.to_csv('gnb_model_test_predictions.csv', index=False)

In [38]:
test_data['Cover_Type'] = df_predictions
test_data.to_csv('bg_model_test_predictions.csv', index=False)